# Generated by Django 4.2.24 on 2025-12-08 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Object ID"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="User name"
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="User email"
                    ),
                ),
                ("user_url", models.URLField(blank=True, verbose_name="User URL")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to hide the comment from public view.",
                        verbose_name="Is public",
                    ),
                ),
                (
                    "is_removed",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box if the comment should be treated as removed.",
                        verbose_name="Is removed",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Used for storing hierarchical comment structure",
                        max_length=255,
                        verbose_name="Materialized path",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Thread ID",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_comments",
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="django_comments.comment",
                        verbose_name="Parent comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ("-created_at",),
                "permissions": [("can_moderate_comments", "Can moderate comments")],
            },
        ),
        migrations.CreateModel(
            name="BannedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banned_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for permanent ban",
                        null=True,
                        verbose_name="Banned Until",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for banning this user", verbose_name="Reason"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_banned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Banned By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_bans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banned User",
                "verbose_name_plural": "Banned Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Comment ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deleted", "Deleted"),
                            ("edited", "Edited"),
                            ("flagged", "Flagged"),
                            ("unflagged", "Unflagged"),
                            ("banned_user", "Banned User"),
                            ("unbanned_user", "Unbanned User"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for this action",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "affected_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Affected User",
                    ),
                ),
                (
                    "comment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Comment Type",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Moderator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Action",
                "verbose_name_plural": "Moderation Actions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["comment_type", "comment_id"],
                        name="modaction_comment_idx",
                    ),
                    models.Index(
                        fields=["moderator", "action"], name="modaction_mod_idx"
                    ),
                    models.Index(fields=["timestamp"], name="modaction_time_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommentRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_id",
                    models.CharField(max_length=255, verbose_name="Comment ID"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Previous version of comment content",
                        verbose_name="Content",
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Edited At"),
                ),
                (
                    "was_public",
                    models.BooleanField(default=True, verbose_name="Was Public"),
                ),
                (
                    "was_removed",
                    models.BooleanField(default=False, verbose_name="Was Removed"),
                ),
                (
                    "comment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Comment Type",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Edited By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Revision",
                "verbose_name_plural": "Comment Revisions",
                "ordering": ["-edited_at"],
                "indexes": [
                    models.Index(
                        fields=["comment_type", "comment_id"],
                        name="commentrev_comment_idx",
                    ),
                    models.Index(fields=["edited_at"], name="commentrev_edited_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommentFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "comment_id",
                    models.CharField(
                        help_text="The ID of the comment (supports both integer and UUID)",
                        max_length=255,
                        verbose_name="Comment ID",
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("hate_speech", "Hate Speech"),
                            ("violence", "Violence/Threats"),
                            ("sexual", "Sexual Content"),
                            ("misinformation", "Misinformation"),
                            ("off_topic", "Off Topic"),
                            ("offensive", "Offensive"),
                            ("inappropriate", "Inappropriate"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                        verbose_name="Flag",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for flagging",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this flag has been reviewed by a moderator",
                        verbose_name="Reviewed",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "review_action",
                    models.CharField(
                        blank=True,
                        choices=[("dismissed", "Dismissed"), ("actioned", "Actioned")],
                        max_length=20,
                        verbose_name="Review Action",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Review Notes"),
                ),
                (
                    "comment_type",
                    models.ForeignKey(
                        help_text="The type of comment being flagged",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Comment Type",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who flagged this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_flags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment flag",
                "verbose_name_plural": "Comment flags",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["comment_type", "comment_id"],
                        name="commentflag_comment_idx",
                    ),
                    models.Index(
                        fields=["user", "flag"], name="commentflag_user_flag_idx"
                    ),
                    models.Index(
                        fields=["flag", "created_at"], name="commentflag_flag_date_idx"
                    ),
                    models.Index(
                        fields=["reviewed", "created_at"], name="commentflag_review_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="commentflag",
            constraint=models.UniqueConstraint(
                fields=("comment_type", "comment_id", "user", "flag"),
                name="unique_comment_flag_per_user",
                violation_error_message="You have already flagged this comment with this flag type.",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="django_comm_content_248d00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="django_comm_created_0a326d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_public", "is_removed"],
                name="django_comm_is_publ_9ca4da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent"], name="django_comm_parent__0cf14a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user"], name="django_comm_user_id_686c85_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["thread_id"], name="django_comm_thread__5f25be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["path"], name="django_comm_path_08ba26_idx"),
        ),
        migrations.AddIndex(
            model_name="banneduser",
            index=models.Index(
                fields=["user", "banned_until"], name="django_comm_user_id_ban_idx"
            ),
        ),
    ]
