# Generated by Django 4.2.24 on 2025-12-04 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UUIDComment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("object_id", models.TextField(verbose_name="Object ID")),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="User name"
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="User email"
                    ),
                ),
                ("user_url", models.URLField(blank=True, verbose_name="User URL")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to hide the comment from public view.",
                        verbose_name="Is public",
                    ),
                ),
                (
                    "is_removed",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box if the comment should be treated as removed.",
                        verbose_name="Is removed",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Used for storing hierarchical comment structure",
                        max_length=255,
                        verbose_name="Materialized path",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Thread ID",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_comments",
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.DJANGO_COMMENTS_COMMENT_MODEL,
                        verbose_name="Parent comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment (UUID)",
                "verbose_name_plural": "Comments (UUID)",
                "ordering": ("-created_at",),
                "permissions": [("can_moderate_comments", "Can moderate comments")],
                "swappable": "DJANGO_COMMENTS_COMMENT_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("object_id", models.TextField(verbose_name="Object ID")),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="User name"
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="User email"
                    ),
                ),
                ("user_url", models.URLField(blank=True, verbose_name="User URL")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this box to hide the comment from public view.",
                        verbose_name="Is public",
                    ),
                ),
                (
                    "is_removed",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box if the comment should be treated as removed.",
                        verbose_name="Is removed",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Used for storing hierarchical comment structure",
                        max_length=255,
                        verbose_name="Materialized path",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Thread ID",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_comments",
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.DJANGO_COMMENTS_COMMENT_MODEL,
                        verbose_name="Parent comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ("-created_at",),
                "permissions": [("can_moderate_comments", "Can moderate comments")],
                "swappable": "DJANGO_COMMENTS_COMMENT_MODEL",
            },
        ),
        migrations.CreateModel(
            name="CommentFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "comment_id",
                    models.TextField(
                        help_text="The ID of the comment (can be integer or UUID)",
                        verbose_name="Comment ID",
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("offensive", "Offensive"),
                            ("inappropriate", "Inappropriate"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                        verbose_name="Flag",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for flagging",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "comment_type",
                    models.ForeignKey(
                        help_text="The type of comment being flagged",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Comment Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who flagged this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_flags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment flag",
                "verbose_name_plural": "Comment flags",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["comment_type", "comment_id"],
                        name="commentflag_comment_idx",
                    ),
                    models.Index(
                        fields=["user", "flag"], name="commentflag_user_flag_idx"
                    ),
                    models.Index(
                        fields=["flag", "created_at"], name="commentflag_flag_date_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="commentflag",
            constraint=models.UniqueConstraint(
                fields=("comment_type", "comment_id", "user", "flag"),
                name="unique_comment_flag_per_user",
                violation_error_message="You have already flagged this comment with this flag type.",
            ),
        ),
        migrations.AddIndex(
            model_name="uuidcomment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="django_comm_content_9b5686_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uuidcomment",
            index=models.Index(
                fields=["created_at"], name="django_comm_created_107198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uuidcomment",
            index=models.Index(
                fields=["is_public", "is_removed"],
                name="django_comm_is_publ_f79ff0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uuidcomment",
            index=models.Index(
                fields=["parent"], name="django_comm_parent__bfe422_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uuidcomment",
            index=models.Index(fields=["user"], name="django_comm_user_id_439c9c_idx"),
        ),
        migrations.AddIndex(
            model_name="uuidcomment",
            index=models.Index(
                fields=["thread_id"], name="django_comm_thread__40ba4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uuidcomment",
            index=models.Index(fields=["path"], name="django_comm_path_2160b6_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="django_comm_content_248d00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="django_comm_created_0a326d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_public", "is_removed"],
                name="django_comm_is_publ_9ca4da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent"], name="django_comm_parent__0cf14a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user"], name="django_comm_user_id_686c85_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["thread_id"], name="django_comm_thread__5f25be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["path"], name="django_comm_path_08ba26_idx"),
        ),
    ]
