# Generated by Django 4.2.24 on 2025-12-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_comments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user_url",
        ),
    ]
