# Generated by Django 4.2.24 on 2025-12-04 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uuidcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to=settings.DJANGO_COMMENTS_COMMENT_MODEL,
                verbose_name="Parent comment",
            ),
        ),
    ]
