# Generated by Django 4.2.24 on 2025-12-02 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_comments", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="django_comm_ct_obj_public_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="django_comm_thread_path_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="django_comm_moderation_queue_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="django_comm_is_publ_a62e5e_idx",
            old_name="django_comm_public_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="django_comm_user_id_83e03a_idx",
            old_name="django_comm_user_created_idx",
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id", "is_public"],
                name="django_comm_content_20fa15_idx",
            ),
        ),
    ]
