# Generated by Django 4.2.24 on 2025-12-02 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_comments",
            "0003_remove_comment_django_comm_ct_obj_public_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="commentflag",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
