# Generated by Django 4.2.24 on 2025-12-11 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_comments", "0003_uuid primary_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentflag",
            name="user",
            field=models.ForeignKey(
                help_text="The user who flagged this comment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comment_flags",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddConstraint(
            model_name="banneduser",
            constraint=models.UniqueConstraint(
                fields=("user",),
                name="unique_banned_user",
                violation_error_message="This user is already banned.",
            ),
        ),
    ]
